version: "3.4"
services:
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: panel
      MYSQL_USER: ptero
      MYSQL_PASSWORD: ptero123
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - db:/var/lib/mysql
  cache:
    image: redis
    restart: always
  php-fpm:
    image: yoshiwalsh/pterodactyl-panel:v1.11.10
    restart: always
    depends_on:
      - database
    volumes:
      - app:/var/www/html/
      - storage:/var/www/html/storage/
      - public:/var/www/html/public/
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: panel
      DB_USERNAME: ptero
      DB_PASSWORD: ptero123
  nginx:
    image: yoshiwalsh/nginx-for-php-fpm
    restart: always
    depends_on:
      - php-fpm
    ports:
      - 80:80
    volumes:
      - public:/var/www/html/

volumes:
  public:
  db:
  storage:
  app:
